### ISSUE TITLE
Excavator and Greataxe only break 1x1

### ISSUE THREAD

**Issue by TookUrSweetRoll** [astradamus/PracticalTools#5]
Not felling trees. Used diamond on oak and spruce.

MC: 1.14.3
PT:  1.2
Forge: v17

**Comment by astradamus** [comment]
Not felling ANY trees? Just specific shapes or?

**Comment by TookUrSweetRoll** [comment]
Takes one log at a time, like regular axe.

**Comment by astradamus** [comment]
This is fixed, pushing the update now. Thank you for pointing this out! I'm an idiot lol.

**Comment by TookUrSweetRoll** [comment]
That's a much better title. :) Thank you.

**Comment by astradamus** [comment]
https://www.curseforge.com/minecraft/mc-mods/practical-tools/files

The new version should be posted and approved within the next few minutes.

Thank you SO MUCH for bringing this to my attention! I guess most people are using this mod for the Hammer, because it took 3 days and 600 downloads before someone noticed that this version broke the Excavator and Greataxe! Whoops ><
